version: "3.3"

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: bkihack
      POSTGRES_USER: bkihack
      POSTGRES_PASSWORD: bkihack
    ports:
      - "5432:5432"